# tạo database trong mysql

CREATE DATABASE web_do_an;

CREATE TABLE roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL
);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hoten VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    email VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    sdt VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    matKhau VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    roleID VARCHAR(255) NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngaySua TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE suppliers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ten VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    diaChi VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    email VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    sdt VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngaySua TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE promotions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code INT NOT NULL,
    noiDung VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    tuNgay DATE NOT NULL,
    denNgay DATE NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngaySua TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    promotionID INT NOT NULL,
    supplierID INT NOT NULL,
    ten VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    moTa TEXT CHARACTER SET UTF8MB4 NOT NULL,
    heDieuHanh VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    anh VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    donGia DECIMAL(10, 2) NOT NULL,
    baoHanh VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    mauSac VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngaySua TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    soLuong INT NOT NULL,
    FOREIGN KEY (promotionID) REFERENCES promotions(id),
    FOREIGN KEY (supplierID) REFERENCES suppliers(id)
);

CREATE TABLE comments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    productID INT NOT NULL,
    noiDung TEXT CHARACTER SET UTF8MB4 NOT NULL,
    trangThai VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngaySua TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES users(id),
    FOREIGN KEY (productID) REFERENCES products(id)
);

CREATE TABLE carts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    productID INT NOT NULL,
    soLuong INT NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngaySua TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES users(id),
    FOREIGN KEY (productID) REFERENCES products(id)
);

CREATE TABLE invoices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    tongTien DECIMAL(10, 2) NOT NULL,
    diaChiGiaoHang TEXT CHARACTER SET UTF8MB4 NOT NULL,
    trangThai VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    phuongThucThanhToan VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngaySua TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES users(id)
);

CREATE TABLE invoiceDetails (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoiceID INT NOT NULL,
    productID INT NOT NULL,
    soLuong INT NOT NULL,
    trangThai VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    tongTien DECIMAL(10, 2) NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngaySua TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (productID) REFERENCES products(id),
    FOREIGN KEY (invoiceID) REFERENCES invoices(id)
);

CREATE TABLE shoppings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoiceID INT NOT NULL,
    userID INT NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngaySua TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (invoiceID) REFERENCES invoices(id),
    FOREIGN KEY (userID) REFERENCES users(id)
);

--set data
INSERT INTO roles (code)
VALUES
  ('ADMIN'),
  ('EMPLOYEE'),
  ('USER', 'Người dùng hệ thống');

